### ISSUE TITLE
[taskmanager]: right-click on a pinned, but not started launcher opens option popup below

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.11#56] opened 2017-02-08 10:28 UTC
![screenshot_20170208_112750](https://cloud.githubusercontent.com/assets/840070/22733344/abb2a958-edf1-11e6-9d5b-3dcf5821e4e5.png)

**Comment by eikehein** [comment] 2017-02-09 09:47
This is kinda sorta not a bug - the only reason the other menus open above is because they don't have enough room to go below ... I can see why for consistency we might want this to go above too though, looking into it.

**Comment by eikehein** [comment] 2017-02-10 12:46
Patches under review:
https://phabricator.kde.org/D4546
https://phabricator.kde.org/D4547

**Comment by eikehein** [comment] 2017-02-10 15:37
Modified version of D4546 is merged now (D4547 is no longer needed). This fix is in plasma-framework and will be released with KF 5.31.

**Comment by star-buck** [comment] 2017-02-10 15:52
Awesome, thanks.

**Comment by star-buck** [comment] 2017-03-03 09:27
@eikehein : 
using plasma5.9.3 and KF5.31 but still same behaviour

**Comment by eikehein** [comment] 2017-03-03 15:58
It's fine here ...

![screenshot_20170304_005735](https://cloud.githubusercontent.com/assets/2744902/23558062/963fcdc6-0075-11e7-91a6-3619cdbc80db.png)

Let me try to find out what happened release-wise.

**Comment by eikehein** [comment] 2017-03-03 16:03
Apparently the fix (701771833ee1d60) isn't in 5.31 sadly, looks like it was tagged before. Fix and tag were on the same day :(.

**Comment by star-buck** [comment] 2017-05-21 08:57
@eikehein : so i guess this is already in some newer version by now?

**Closed** 2018-01-10 00:25 UTC
Labels: ready for QA
